# [作業目標]
- 利用範例的創建方式, 創建一組資料, 並練習如何取出最大值

# [作業重點]
- 練習創立 DataFrame (In[2])
- 如何取出口數最多的國家 (In[3], Out[3])

## 練習時間
在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

#### Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家

### Hints: [隨機產生數值](https://blog.csdn.net/christianashannon/article/details/78867204)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.random.rand(10)
print(type(np.random.rand(10)))

<class 'numpy.ndarray'>

In [ ]:
data = {'國家':['台灣','中國','韓國','日本'] ,
        '人口':(np.random.rand(4)*1000).tolist() }  #隨機產生一個有4個element的ndarray，再將此ndarray轉為list
print(data)
print(type(data))
data = pd.DataFrame(data) #用pd.DataFrame將dict做成表格
data

{'國家': ['台灣', '中國', '韓國', '日本'], '人口': [140.5095131902837, 127.84457326017085, 168.5046096267816, 951.8849838940248]}
<class 'dict'>

   國家          人口
0  台灣  140.509513
1  中國  127.844573
2  韓國  168.504610
3  日本  951.884984

In [ ]:
max_num=data.loc[:,"人口"].max()  #取出最多人口數值
print(max_num)
print(data['人口'] == max_num)  
max=data.loc[data['人口'] == max_num] #用布林函數取值
max

951.8849838940248
0    False
1    False
2    False
3     True
Name: 人口, dtype: bool

   國家          人口
3  日本  951.884984